default:
  image: node:16.16.0

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=IKxh9tEqEUWw206qcm7iSPSX
    - vercel build --token=IKxh9tEqEUWw206qcm7iSPSX
    - vercel deploy --prebuilt  --token=IKxh9tEqEUWw206qcm7iSPSX

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=IKxh9tEqEUWw206qcm7iSPSX
    - vercel build --prod --token=IKxh9tEqEUWw206qcm7iSPSX
    - vercel deploy --prebuilt --prod --token=IKxh9tEqEUWw206qcm7iSPSX