# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-paginate-v2
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-dotenv
- jekyll-notion

# notion:
#   fetch_on_watch: true
#   databases:
#     - id: a70e6d4a7f03492c93f3846c73f24700
#       collection: posts
#       filter: { "property": "Published", "checkbox": { "equals": true } }

# 3. Gem settings
# Pagination Setting
############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 25

  # The permalink structure for the paginated pages (this can be any level deep)
  
  # permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  # permalink: '/page/:num.html' # Pages are simple html files 
  # permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  permalink: '/page=:num/' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # 
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 8

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################

jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Wizideals # jekyll-seo-tag > Owners twitter username
author: Wizideals # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Wizideals # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Wizideals

# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: none  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    output: true

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Wizideals" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Welcome to Wizideals, your one-stop destination for unbeatable deals and discounts! We are a curated website that scours the internet to bring you the best deals on a wide variety of products and services. Our team of experts works tirelessly to find the latest and greatest deals on everything from clothing to shooes, accessories and beauty products. We only feature deals from trusted retailers and brands, so you can shop with confidence knowing you're getting a great value for your money.

At Wizideals, we understand that everyone loves a great deal, which is why we strive to bring you the best discounts and promotions on a wide range of products. We've got you covered.

We also have a special section for time-limited deals, so you never miss out on a great opportunity to save. And with new deals added regularly, you'll always find something new and exciting on our website.

So why wait? Browse our selection of deals today and start saving on your favorite products and services. Happy shopping with Wizideals!"
url: "https://wizideals.com" # Site url, also used in jekyll-seo-tag
baseurl: ""

# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
google_analytics: "345040285"
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  # 16: '/assets/logos/logo@16px.png'
  # 32: '/assets/logos/logo@32px.png'
  # 96: '/assets/logos/logo@96px.png'
  # 120: '/assets/logos/logo@120px.png'
  # 144: '/assets/logos/logo@144px.png'
  # 180: '/assets/logos/logo@180px.png'
  # 512: '/assets/logos/logo@512px.png'
  # 1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Women
  url: /women/
- title: Men
  url: /men/
- title: Kids
  url: /kids/


brands:
- brand: cotton:on
  url: https://invol.co/clgfxxy?url=
- brand: jdsports
  url: https://invol.co/clh3ej2?url=
- brand: hermo
  url: https://invol.co/clh3eu5?url=
- brand: puma
  url: https://invle.co/clh3ec2?url=
- brand: skechers
  url: https://invol.co/clh306o?url=
- brand: adidas
  url: https://invol.co/clh305o?url=
- brand: sephora
  url: https://invol.co/clh2x87?url=
- brand: zalora
  url: https://invle.co/clgfy1q?url=
- brand: charles-kieth
  url: https://click.accesstra.de/adv.php?rk=009via001ywf&url=https%3A%2F%2Fcharleskeithmy.pxf.io%2Fc%2F2059500%2F1078154%2F13802%3FsubId1%3D%7Bclickid%7D%26subId2%3D%7Bcampaign%7D%26subId3%3D%7Bpublisher_site_url%7D%26sharedid%3D%7Bpsn%7D%26u%3D
- brand: under-armour
  url: https://click.accesstra.de/adv.php?rk=00af09001ywf&url=https%3A%2F%2Fclk.omgt3.com%2F%3FAID%3D2131604%26PID%3D51182%26UID%3D%7Bclickid%7D%26UID2%3D%7Bcampaign%7D%26UID3%3D3%26r%3D
- brand: love-bonito
  url: https://imp.i163678.net/c/2059500/821353/11588?subId1={gclid}&subId2=91887&svlink=4697231&u=







navigation_footer:
- title: Wizideals
  url: https://wizideals.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/Wizideals
  link: https://wizideals.com
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  pinterest: true
  reddit: true
  whatsapp: true
  Email: true





# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap


