# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-dotenv
- jekyll-notion

notion:
  fetch_on_watch: true
  databases:
    - id: a70e6d4a7f03492c93f3846c73f24700
      collection: posts
      filter: { "property": "Published", "checkbox": { "equals": true } }

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: deals/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Wizideals # jekyll-seo-tag > Owners twitter username
author: Wizideals # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Wizideals # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Wizideals

# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: none  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    output: true

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Wizideals" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Welcome to Wizideals, your one-stop destination for unbeatable deals and discounts! We are a curated website that scours the internet to bring you the best deals on a wide variety of products and services. Our team of experts works tirelessly to find the latest and greatest deals on everything from clothing to shooes, accessories and beauty products. We only feature deals from trusted retailers and brands, so you can shop with confidence knowing you're getting a great value for your money.

At Wizideals, we understand that everyone loves a great deal, which is why we strive to bring you the best discounts and promotions on a wide range of products. We've got you covered.

We also have a special section for time-limited deals, so you never miss out on a great opportunity to save. And with new deals added regularly, you'll always find something new and exciting on our website.

So why wait? Browse our selection of deals today and start saving on your favorite products and services. Happy shopping with Wizideals!"
url: "" # Site url, also used in jekyll-seo-tag
baseurl: ""

# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Deals
  url: /deals/
- title: Categories
  url: /categories/
- title: Search
  url: /search/

brands:
- brand: cotton
  url: https://invol.co/clgfxxy?url=
- brand: jdsports
  url: https://invol.co/clh3ej2?url=
- brand: hermo
  url: https://invol.co/clh3eu5?url=
- brand: puma
  url: https://invle.co/clh3ec2?url=
- brand: skechers
  url: https://invol.co/clh306o?url=
- brand: addidas
  url: https://invol.co/clh305o?url=
- brand: sephora
  url: https://invol.co/clh2x87?url=
- brand: zalora
  url: https://invle.co/clgfy1q?url=
- brand: charles&kieth
  url: https://click.accesstra.de/adv.php?rk=009via001ywf&url=https%3A%2F%2Fcharleskeithmy.pxf.io%2Fc%2F2059500%2F1078154%2F13802%3FsubId1%3D%7Bclickid%7D%26subId2%3D%7Bcampaign%7D%26subId3%3D%7Bpublisher_site_url%7D%26sharedid%3D%7Bpsn%7D%26u%3D
- brand: under-armour
  url: https://click.accesstra.de/adv.php?rk=00af09001ywf&url=https%3A%2F%2Fclk.omgt3.com%2F%3FAID%3D2131604%26PID%3D51182%26UID%3D%7Bclickid%7D%26UID2%3D%7Bcampaign%7D%26UID3%3D3%26r%3D







navigation_footer:
- title: Wizideals
  url: https://wizideals.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/Wizideals
  link: https://https://wizideals.com
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  pinterest: true
  reddit: true
  whatsapp: true
  Email: true





# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap


